[tools]
dotnet = "9"

[tasks.setup-binaryen]
run = "bash -c 'source ./scripts/setup-binaryen.sh'"

[tasks.build]
run = "bash -c 'source ./scripts/setup-binaryen.sh && dotnet build -c Release'"

[tasks.aot-linux-x64]
run = "bash -c 'source ./scripts/setup-binaryen.sh && dotnet publish src/Brim.Tool -c Release -r linux-x64 -p:PublishAot=true -p:StripSymbols=true -p:InvariantGlobalization=true'"

[tasks.test]
run = "bash -c 'source ./scripts/setup-binaryen.sh && dotnet test -c Release --results-directory out/test-results --logger \"trx;LogFileName=test-results.trx\"'"
