[tools]
dotnet = "9"

[tasks.build]
run = "dotnet build -c Release"
[tasks.aot-linux-x64]
run = "dotnet publish src/Brim.Tool -c Release -r linux-x64 -p:PublishAot=true -p:StripSymbol=true -p:InvariantGlobalization=true"
[tasks.test]
run = "dotnet test -c Release --results-directory out/test-results --logger \"trx;LogFileName=test-results.trx\""
