namespace Brim.Parse.Green;

public enum SyntaxKind
{
  Undefined = -1,
  // Tokens
  ErrorToken = 0,
  ModulePathOpenToken,
  ModulePathCloseToken,
  ModulePathSepToken,
  ModuleBindToken,
  IdentifierToken,
  IntToken,
  DecimalToken,
  StrToken,
  QuestionToken,
  BangToken,
  EqualToken,
  TypeBindToken,
  LessToken,
  GreaterToken,
  UnionToken,
  AmpersandToken,
  OpenBraceToken,
  CloseBlockToken,
  ExportMarkerToken,
  ColonToken,
  CommaToken,
  PlusToken,
  GenericOpenToken,
  GenericCloseToken,
  OpenParenToken,
  CloseParenToken,
  TerminatorToken,
  StopToken,
  HatToken,
  TildeToken,
  NamedTupleToken,
  ProtocolToken,
  StructToken,
  ServiceToken,
  EobToken,

  // Nodes
  Module,

  // Declarations
  TypeDeclaration,
  FunctionDeclaration,
  ValueDeclaration,
  ProtocolDeclaration,
  ServiceDeclaration,
  FunctionShape,
  MethodSignature,
  ExportDirective,
  ImportDeclaration,
  ParameterList,
  GenericParameterList,
  GenericArgumentList,
  GenericParameter,
  ConstraintList,
  ConstraintRef,
  BlockExpr,
  ModuleHeader,
  ModulePath,
  ModuleDirective,
  UnionVariantDeclaration,
  GenericType,

  // Type expression nodes
  StructShape,
  UnionShape,
  FlagsShape,
  NamedTupleShape,
  ProtocolShape,
  ServiceShape,
  DeclarationName,
  GenericArgument,
  NamedTupleElement,
  FlagMemberDeclaration,
  ImplementsRef,
  FunctionParameter,
  FieldDeclaration,
  FieldList,
  ServiceImplToken,
}
