namespace Brim.Parse.Green;

public enum SyntaxKind
{
  // Tokens
  ErrorToken,
  ModulePathOpenToken,
  ModulePathCloseToken,
  ModulePathSepToken,
  ModuleBindToken,
  IdentifierToken,
  IntToken,
  DecimalToken,
  StrToken,
  QuestionToken,
  BangToken,
  EqualToken,
  TypeBindToken,
  LessToken,
  GreaterToken,
  StructToken,
  UnionToken,
  AmpersandToken,
  OpenBraceToken,
  CloseBraceToken,
  ExportMarkerToken,
  ColonToken,
  CommaToken,
  PlusToken,
  GenericOpenToken,
  GenericCloseToken,
  OpenParenToken,
  CloseParenToken,
  TerminatorToken,
  EobToken,
  NamedTupleToken,
  ProtocolToken,
  StopToken,
  HatToken,

  // Nodes
  Module,
  // Declarations
  TypeDeclaration,
  FunctionDeclaration,
  ProtocolDeclaration,
  ServiceDeclaration,
  FunctionShape,
  MethodSignature,
  ExportDirective,
  ImportDeclaration,
  ParameterList,
  GenericParameterList,
  GenericArgumentList,
  GenericParameter,
  ConstraintList,
  ConstraintRef,
  FieldList,
  Block,
  ModuleHeader,
  ModulePath,
  ModuleDirective,
  FieldDeclaration,
  UnionVariantDeclaration,
  FlagMemberDeclaration,
  GenericType,
  // Type expression nodes
  StructShape,
  UnionShape,
  FlagsShape,
  NamedTupleShape,
  ProtocolShape,
  ServiceShape,
  DeclarationName,
  GenericArgument,
  NamedTupleElement,
  ImplementsRef,
  FunctionParameter,
}
