namespace Brim.Parse.Green;

public enum SyntaxKind
{
  // Tokens
  ErrorToken,
  ModulePathOpenToken,
  ModulePathCloseToken,
  ModulePathSepToken,
  IdentifierToken,
  IntToken,
  DecimalToken,
  StrToken,
  EqualToken,
  StructToken,
  UnionToken,
  AmpersandToken,
  OpenBraceToken,
  CloseBraceToken,
  ExportMarkerToken,
  ColonToken,
  CommaToken,
  GenericOpenToken,
  GenericCloseToken,
  TerminatorToken,
  EobToken,
  NamedTupleToken,

  // Nodes
  Module,
  FunctionDeclaration,
  StructDeclaration,
  UnionDeclaration,
  FlagsDeclaration,
  ExportDirective,
  ImportDeclaration,
  ParameterList,
  GenericParameterList,
  GenericArgumentList,
  GenericParameter,
  ConstraintList,
  FieldList,
  Block,
  ModuleHeader,
  ModulePath,
  ModuleDirective,
  FieldDeclaration,
  UnionVariantDeclaration,
  FlagMemberDeclaration,
  GenericType,
  NamedTupleDeclaration,
  DeclarationName,
  GenericArgument,
  NamedTupleElement,
  // Expressions (seed)
  UnionConstructorExpr,
  UnionConstructorEntry,
}
