name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - run: mise install
      - run: dotnet --info
      - run: dotnet build -c Release
      - run: dotnet test  -c Release
      - run: dotnet publish src/Brim.Tool -c Release -r linux-x64 -p:PublishAot=true -p:StripSymbols=true -p:InvariantGlobalization=true -o out/linux-x64
      - run: ./out/linux-x64/Brim.Tool version
