name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - run: mise install
      - run: dotnet --info
      - run: mise run lint
      - run: mise run test
      - run: mise run aot:linux-x64:publish
      - run: artifacts/publish/Brim.Tool/release_linux-x64/Brim.Tool --version

